### ISSUE TITLE
Create IBig from arrays/mod_pow?

### ISSUE THREAD

**Issue by username223** [tczajka/ibig-rs#6]
Hello,

Thanks for the excellent library and [bigint comparison](https://lib.rs/crates/bigint-benchmark). I'm unsure if this functionality is present since the docs do not mention it, but is it possible to create an IBig from an array/slice? It only seems to be possible to create them from strings, and since I already have my values as arrays on the stack it doesn't make much sense to allocate and convert to a string only to parse it and convert back.

I'm writing a small library with very well defined integer limits of at most 32 bytes, so if possible I would like to avoid allocations at all and just do operations on stack arrays.

I also can't find a [mod_pow](https://docs.rs/num-bigint/0.4.0/num_bigint/struct.BigInt.html#method.modpow) equivalent, is that included?

Thanks :)

**Comment by vks** [comment]
@username223 I have a generic implementation of `mod_pow` in [this open PR](https://github.com/rust-num/num-integer/pull/10). It should work with ibig if you implement the num-integer traits. Alternatively, see my code [here](https://github.com/vks/discrete-log), which already works with ibig.

**Comment by vks** [comment]
I found the modular exponentiation [here](https://docs.rs/ibig/0.3.2/ibig/modular/struct.Modulo.html#method.pow).

**Comment by vks** [comment]
@username223 [This](https://docs.rs/ibig/0.3.2/ibig/struct.UBig.html#method.from_le_bytes) let's you create a `UBig` from a `&[u8]`.

**Comment by tczajka** [comment]
To summarize:

Conversion from bytes already exists as `UBig::from_le_bytes` and `UBig::from_be_bytes`. Is this sufficient?

Modular exponentiation already exists as `ibig::modular::Modulo::pow`.

Integers bigger than 8 bytes (on 64-bit systems) currently allocate on the heap. This may change in the future, with something like 24 or 32 bytes not requiring an allocation (since this can be done without increasing `mem::size_of<UBig>()`), but let's keep that out of the scope of this ticket.

**Comment by username223** [comment]
@vks @tczajka
Ah yes, that seems to do. I'm not sure how I missed that. Thanks for the help. :)
